# Generated by Django 4.2.4 on 2023-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_party_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='alias',
            field=models.CharField(default=models.CharField(max_length=30), max_length=10),
        ),
    ]
