# Generated by Django 4.2.4 on 2023-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_invoice_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='qty',
            field=models.FloatField(),
        ),
    ]
