# Generated by Django 4.2.4 on 2023-08-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_entry_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
