# Generated by Django 4.2.4 on 2023-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_entry_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pts',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
