# Generated by Django 4.2.4 on 2023-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_entry_pts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ptr',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pts',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
