# Generated by Django 4.2.4 on 2023-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_entry_mrp_alter_entry_ptr_alter_entry_pts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
