# Generated by Django 4.2.4 on 2023-08-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_entry_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusAndGST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=0)),
                ('gstrate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SavedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoicenumber', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(blank=True, max_length=20, null=True)),
                ('address3', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('gstid', models.CharField(max_length=20)),
                ('dlno', models.CharField(max_length=20)),
                ('gst', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaveEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.IntegerField()),
                ('sno', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('mfg', models.CharField(max_length=20)),
                ('batchNo', models.CharField(max_length=10)),
                ('expiry', models.CharField(max_length=15)),
                ('mrp', models.CharField(max_length=8)),
                ('ptr', models.CharField(max_length=8)),
                ('pts', models.CharField(max_length=8)),
                ('qty', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
    ]
