# Generated by Django 4.2.4 on 2023-08-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bonusandgst_savedinvoice_saveentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveentries',
            name='pack',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
