# Generated by Django 4.2.4 on 2023-08-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_saveentries_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedinvoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
