# Generated by Django 4.2.4 on 2023-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_savedinvoice_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('dlno', models.CharField(max_length=20)),
                ('gst', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterModelOptions(
            name='saveentries',
            options={'ordering': ['sno']},
        ),
    ]
