# Generated by Django 4.2.4 on 2023-08-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_companydetails_alter_saveentries_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-expiry', 'product']},
        ),
    ]
