# Generated by Django 4.2.4 on 2023-08-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_products_options_alter_stock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='mbno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
