# Generated by Django 4.2.4 on 2023-09-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rateentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveRateEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.IntegerField()),
                ('sno', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('pack', models.CharField(default=0, max_length=10)),
                ('mfg', models.CharField(max_length=20)),
                ('batchNo', models.CharField(max_length=10)),
                ('expiry', models.CharField(max_length=15)),
                ('mrp', models.CharField(max_length=8)),
                ('rate', models.CharField(default=None, max_length=8)),
                ('qty', models.IntegerField()),
                ('amount', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['sno'],
            },
        ),
        migrations.AddField(
            model_name='savedinvoice',
            name='rate',
            field=models.BooleanField(default=False),
        ),
    ]
